---

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: US/Eastern
    commit-message:
      prefix: "Dependabot - NPM: "
      include: "scope"
    labels:
      - "npm"
      - "dependencies"
    pull-request-branch-name:
      separator: "-"
