language: node_js

node_js:
 - "node"

before_install: npm install greenkeeper-lockfile@1 --global

before_script: greenkeeper-lockfile-update

install:
  - npm install codecov --global
  - npm install

script:
 - npm run test
 - codecov

after_script: greenkeeper-lockfile-upload
