language: node_js

node_js:
 - "11"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn global add codecov
  - yarn install

script:
 - yarn run test --maxWorkers=4
 - codecov
