language: node_js

node_js:
 - "node"

before_install: yarn global add greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update

install:
  - yarn global add codecov
  - yarn install

script:
 - yarn run test
 - codecov

after_script: greenkeeper-lockfile-upload
